### ISSUE TITLE
Vereinsmanagment

### ISSUE THREAD

**Issue by TorstenK84** [jensDebernitz/GroundHopping#2]
Es soll eine neue maske geben "Verein eintragen" in der ich Vereine Eintragen kann. Diesem Verein wird eindeutig ein Bundesland zugewiesen.
Auf der anderen Seite(beim eintragen der Spiele) dürfen nur Vereine ausgewählt werden die auf der Seite "Verein eintragen" eingetragen wurden.

**Comment by jensDebernitz** [comment]
ist implementiert
